#!/usr/bin/env python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

os.environ["GIMIC_LAUNCHER"] = "valgrind --tool=memcheck --log-file=valgrid-summary.dat --leak-check=full --track-origins=yes --show-reachable=yes -v"

options = cli()

f = [
     get_filter(from_string='in use at exit',
                num_lines=1,
                rel_tolerance=0),
     get_filter(from_string='ERROR SUMMARY',
               to_string='errors from',
               rel_tolerance=0),
     ]
acc = [
     get_filter(from_string=' *** Integrating current',
               num_lines=10,
               rel_tolerance=1.0e-8),
    ]

ierr = run(options,
           configure,
           input_files=['gimic.inp'],
           filters={'valgrid-summary.dat': f,
	            'stdout': acc})

sys.exit(ierr)

os.environ["GIMIC_LAUNCHER"] = ""
