#!/bin/sh

snykov() {
BLASDIR=/opt/intel/cmkl/8.0/lib/64
INSTDIR=$HOME/gimic
case $* in 
	--mpi) 
	MPIFC=scampif90 ./configure --prefix=${INSTDIR} \
	--with-fc-search-path=$HOME/flibs --with-blas-dir=$BLASDIR \
	--with-aces2=$HOME/aces2/lib --enable-mpi
	;;
	*)
	./configure --prefix=${INSTDIR} --with-blas-dir=$BLASDIR \
	--with-fc-search-path=$HOME/flibs --with-aces2=$HOME/aces2/lib
	;;
esac
}

stallo() {
INSTDIR=$HOME/gimic
case $* in 
	--mpi) 
	FC=ifort MPIFC=mpif90 ./configure --prefix=${INSTDIR} \
	--enable-mpi --with-aces2=$HOME/aces2/lib
	;;
	*)
	FC=ifort ./configure --prefix=${INSTDIR} --with-aces2=$HOME/aces2/lib
	;;
esac
}

snowflake() {
BLASDIR=/opt/lib
INSTDIR=/opt/aces2
case $* in
	--mpi) 
	./configure --prefix=${INSTDIR}.par --with-blas-dir=$BLASDIR --enable-mpi
	;;
	*)
	./configure --prefix=${INSTDIR} --with-blas-dir=$BLASDIR \
	--with-fc-search-path=/opt/flibs \
	--with-aces2=$HOME/software/mainz/aces2/lib
	;;
esac
}

case `hostname` in 
	compute-0-6.*) snykov $* ;;
	stallo-*) stallo $* ;;
	snowflake*) snowflake $* ;;
	*) echo "unknown machine..."; exit 0 ;;
esac

