#!/bin/bash 

PREFIX="--prefix=`pwd`"
PARAFLAGS=""

getflgs () {
	for i in $*; do
		case $i in
			--nopara*) PARAFLAGS=""
			--para*) PARAFLAGS="--enable-mpi=openmpi" ;;
			--prefix*) PREFIX=$i ;;
		esac
	done	
}

stallo() {
	if [ -f /etc/profile.d/modules.sh ]; then
		. /etc/profile.d/modules.sh
		module load python
	fi
	BLASDIR="/opt/intel/mkl/10.0.011"
	BLAS="--with-blasdir=$BLASDIR/lib/em64t"
	PYTHON="--with-python=/global/apps/python/2.5.1"
	CC=icc FC=ifort ./configure $PREFIX $PYTHON $PARAFLAGS $BLAS
}

linux() {
	CC=gcc FC=gfortran ./configure $PREFIX $PYTHON $PARAFLAGS $BLAS
}

generic () {
	./configure $PREFIX $PYTHON $PARAFLAGS $BLAS
}

fedora() {
	BLAS="--with-blasdir=/usr/lib/atlas"
	CC=gcc FC=gfortran ./configure $PREFIX $PYTHON $PARAFLAGS $BLAS
}

ubuntu () {
	CC=gcc FC=gfortran ./configure $PREFIX $PYTHON $PARAFLAGS $BLAS
}

macosx() {
	BLAS="--with-blasdir=/opt/local/lib" 
	CC=gcc FC=gfortran ./configure $PREFIX $PYTHON $PARAFLAGS $BLAS
}

getflgs $*

# First we try specific hosts
case `hostname` in
	stallo*) stallo $*; exit 0 ;;
esac

case `uname` in
	Linux*)
		if [ -f /etc/lsb-release ]; then
			. /etc/lsb-release
		else if [ -f /etc/system-release ]; then
			grep -q Fedora /etc/system-release
			if [ $? = 0 ]; then
				DISTRIB_ID="Fedora"
			else 
				echo "Unknown Linux distribution. Using generic config."
				DISTRIB_ID="Linux"
			fi
		fi; fi

		case $DISTRIB_ID in
			*buntu*) 
			   ubuntu $*; exit 0;
			;;
			*edora*) 
			   fedora $*; exit 0;
			;;
			Linux) 
			   linux $*; exit 0;
			;;
		esac
	;;
	Darwin)
		macosx $*; exit 0;
	;;
esac

echo "Unknown host type. Trying generic configuration." 
echo "  Press enter to continue."
read a

generic $*
