#!/usr/bin/env python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

os.environ["GIMIC_LAUNCHER"] = "valgrind --tool=memcheck --log-file=valgrind-summary.dat --leak-check=summary --show-reachable=yes"

options = cli()

# checking the valgrind report
f = [
     get_filter(from_string='in use at exit',
                num_lines=1,
                rel_tolerance=0),
     get_filter(from_string='ERROR SUMMARY',
               to_string='errors from',
               rel_tolerance=0)
     ]
# checking the jvec file
acc = [get_filter(rel_tolerance=1.0e-8)]
ierr = run(options,
           configure,
           input_files=['gimic.inp'],
	   filters={'jvec.vti': acc, 
	        'valgrind-summary.dat': f} )

sys.exit(ierr)

os.environ["GIMIC_LAUNCHER"] = ""
