#!/usr/bin/env python3

import os
import sys
import subprocess

os.environ["GIMIC_LAUNCHER"] = "valgrind --tool=memcheck --leak-check=summary --show-reachable=yes"

assert len(sys.argv) > 1, "you have to give the launcher as argument"
launcher = sys.argv[-1]

proc = subprocess.Popen([launcher, 'gimic.inp'],
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        encoding="utf8",
                        )
stdout, stderr = proc.communicate()

assert 'no leaks are possible' in stderr
assert 'ERROR SUMMARY: 0 errors from 0 contexts' in stderr
