#!/usr/bin/env python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from runtest import version_info, get_filter, cli, run
from runtest_config import configure

assert version_info.major == 2

options = cli()

# we check entire files
f = [get_filter(rel_tolerance=1.0e-8)]

ierr = run(options,
           configure,
           input_files=['gimic.inp'],
           filters={'acid.vti': f,
                    'jmod.vti': f,
                    'jvec.vti': f})

sys.exit(ierr)
