#!bin/bash
# Submit the calculation

wrkdir=$(pwd)
wrkdir=$(echo $wrkdir/$dirname)
echo "Working directory:"; echo $wrkdir; echo
checkIfEmpty wrkdir $wrkdir

echo "Running Gimic calculations..."

filenum=$( (cd $wrkdir && find . -maxdepth 1 -type f -name '*.inp' | wc -l))
checkIfEmpty filenum $filenum

nstepsV=$( sed -n -e 's/^.*nstepsV=//p' $wrkdir/calculation.dat | awk '{print $1}')
checkIfEmpty nstepsV $nstepsV

parallel=4
echo "Enter the number of parallel jobs"
read parallel
checkIfEmpty parallel $parallel

# check if too many parallel tasks are called
if [ $parallel -gt $filenum ]
then
    $parallel=$(echo $filenum)
fi

rm -rf *out *dat *eps GIMIC.*
echo
date
echo "Running $parallel out of $filenum GIMIC calculations at a time..."

for ((col=0; col<$nstepsV; col++))
do
    counter=$(( $counter+1 ))
    idxH=$(echo $file | sed -e "s#\.# #g" | awk '{ print $2}' )
    idxV=$(echo $file | sed -e "s#\.# #g" | awk '{ print $3}' )
#    echo $file " == gimic.$idxH.$idxV.inp"
    cd $wrkdir && gimic gimic.$idxH.$idxV.inp > $wrkdir/gimic.$idxH.$idxV.out &
    if [ $counter -eq $parallel ]
    then
	wait
	counter=0
	completed=$(( $completed*$parallel ))
	date
	echo "$completed out of $filenum jobs completed"; echo
    fi
done



rm -rf GIMIC* 


#######################################################################
# Find the zeroes on the current profile plot

(cd $wrkdir && @SCRIPTS_DIR@/gradient-square.sh  )
#@SCRIPTS_DIR@/gradient-square.sh

#cat $wrkdir/profile-points.out

#######################################################################

echo
