Document: gimic
Title: Debian gimic Manual
Author: <insert document author here>
Abstract: This manual describes what gimic is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gimic/gimic.sgml.gz

Format: postscript
Files: /usr/share/doc/gimic/gimic.ps.gz

Format: text
Files: /usr/share/doc/gimic/gimic.text.gz

Format: HTML
Index: /usr/share/doc/gimic/html/index.html
Files: /usr/share/doc/gimic/html/*.html

  
