#!/bin/bash -l
#SBATCH -p parallel
#SBATCH --nodes 1         # for SMP only 1 is possible
#SBATCH --ntasks-per-node=24 # Tasks per node
#SBATCH --ntasks 24      # total number of cores (processes)
#SBATCH -t 16:00:00        # time as hh:mm:ss
#SBATCH --mem-per-cpu=1000
#SBATCH -e jobfile.err%J
#SBATCH -o jobfile.out%J
#SBATCH --mail-type=END
#SBATCH --mail-user=maria.dimitrova@helsinki.fi

