include(SaveCompilerFlags)

if (NOT DEFINED HAVE_C_FLAGS)
if (CMAKE_COMPILER_IS_GNUCC)
    set (CMAKE_C_FLAGS "-Wall -Wno-sign-compare")
    set (CMAKE_C_FLAGS_DEBUG "-O0 -g3 -DDEBUG")
    set (CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG -Wno-unused")
    if (ENABLE_CODE_COVERAGE)
        set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} --coverage")
    endif()
elseif (CMAKE_C_COMPILER_ID MATCHES Intel)
    set (CMAKE_C_FLAGS "")
    set (CMAKE_C_FLAGS_DEBUG "-O0 -g -DDEBUG")
    set (CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG")
    set (CMAKE_C_LINK_FLAGS "${CMAKE_C_LINK_FLAGS} -shared-intel")
endif ()
save_compiler_flags(C)
endif ()
